using ClosedXML.Excel;
using Microsoft.JSInterop;
using Pobytne.Shared.Procedural;
using System.IO;

namespace Pobytne.Client.Services
{
	public class ExcelExportService
	{
		public static readonly string Evidence_FileName = "Evidence";
		public static readonly string CashRegister_FileName = "Pokladna";
		public static readonly string _FileName = "Sklad";
		public static readonly int startIdx = 3;
		public readonly IJSRuntime _jsRuntime;
		public ExcelExportService(IJSRuntime js) => _jsRuntime = js;
		public async Task ExportData(List<CashRegister> data)
		{
			var wb = new XLWorkbook();
			wb.Properties.Author = "Auto generated by Pobytne BlazorWASM application";
			wb.Properties.Title = $"Souhrny-{CashRegister_FileName}";

			var ws = wb.Worksheets.Add($"Souhrny_{CashRegister_FileName}_{DateTime.Today.ToShortDateString()}");
			ws.Cell(1, 1).Value = $"Auto generated by Pobytne BlazorWASM application at {DateTime.Now}";

			ws.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
			var headerColor = XLColor.LightSteelBlue;
			var borderLine = XLBorderStyleValues.Thin;

			ws.Cell(startIdx, 1).Value = "Id";
			ws.Cell(startIdx, 2).Value = "Datum";
			ws.Cell(startIdx, 3).Value = "Název položky";
			ws.Cell(startIdx, 4).Value = "Popis";
			ws.Cell(startIdx, 5).Value = "Částka";
			ws.Cell(startIdx, 6).Value = "Uživatel";
			ws.Cell(startIdx, 7).Value = "Změnil";
			ws.Cell(startIdx, 8).Value = "Zmeněno";

			// fit the content
			ws.Column(2).AdjustToContents();	
			ws.Column(3).AdjustToContents();
			ws.Column(6).AdjustToContents();
			ws.Column(7).AdjustToContents();
			ws.Column(8).AdjustToContents();
			// Formátování buněk pro třetí řádek (hlavička)
			for (int col = 1; col <= 8; col++)
			{
				ws.Cell(startIdx, col).Style.Fill.BackgroundColor = headerColor;
				ws.Cell(startIdx, col).Style.Border.BottomBorder = borderLine;
				ws.Cell(startIdx, col).Style.Font.Bold = true;
			}


			for (int row = 0; row < data.Count; row++)
			{
				ws.Cell(row + startIdx+1, 1).Value = data[row].Id;
				ws.Cell(row + startIdx+1, 2).Value = data[row].InteractionDate.ToShortDateString();
				ws.Cell(row + startIdx+1, 3).Value = data[row].RecordName;
				ws.Cell(row + startIdx+1, 4).Value = data[row].InteractionDescription;
				ws.Cell(row + startIdx+1, 5).Value = data[row].Price;
				ws.Cell(row + startIdx+1, 6).Value = data[row].CustomerName;
				ws.Cell(row + startIdx+1, 7).Value = data[row].CreationUserName;
				ws.Cell(row + startIdx+1, 8).Value = data[row].CreationDate;
			}

			MemoryStream XLSStream = new();
			wb.SaveAs(XLSStream);

			await DownloadAync(CashRegister_FileName,XLSStream);
		}
		public async Task ExportData(List<Evidence> data)
		{
			var wb = new XLWorkbook();
			wb.Properties.Author = "Auto generated by Pobytne BlazorWASM application";
			wb.Properties.Title = $"Souhrny-{Evidence_FileName}";

			var ws = wb.Worksheets.Add($"Souhrny_{Evidence_FileName}_{DateTime.Today.ToShortDateString()}");
			ws.Cell(1, 1).Value = $"Auto generated by Pobytne BlazorWASM application at {DateTime.Now}";

			ws.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
			var headerColor = XLColor.LightSteelBlue;
			var borderLine = XLBorderStyleValues.Thin;

			ws.Cell(startIdx, 1).Value = "Id";
			ws.Cell(startIdx, 2).Value = "Datum";
			ws.Cell(startIdx, 3).Value = "Název položky";
			ws.Cell(startIdx, 4).Value = "Popis";
			ws.Cell(startIdx, 5).Value = "Kusy";
			ws.Cell(startIdx, 6).Value = "Dospělí";
			ws.Cell(startIdx, 7).Value = "Dítě";
			ws.Cell(startIdx, 8).Value = "Uživatel";
			ws.Cell(startIdx, 9).Value = "Změnil";
			ws.Cell(startIdx, 10).Value = "Zmeněno";

			// fit the content
			ws.Column(2).AdjustToContents();
			ws.Column(3).AdjustToContents();
			ws.Column(5).AdjustToContents();
			ws.Column(6).AdjustToContents();
			ws.Column(7).AdjustToContents();
			// Formátování buněk pro třetí řádek (hlavička)
			for (int col = 1; col <= 10; col++)
			{
				ws.Cell(startIdx, col).Style.Fill.BackgroundColor = headerColor;
				ws.Cell(startIdx, col).Style.Border.BottomBorder = borderLine;
				ws.Cell(startIdx, col).Style.Font.Bold = true;
			}


			for (int row = 0; row < data.Count; row++)
			{
				ws.Cell(row + startIdx + 1, 1).Value = data[row].Id;
				ws.Cell(row + startIdx + 1, 2).Value = data[row].InteractionDate.ToShortDateString();
				ws.Cell(row + startIdx + 1, 3).Value = data[row].RecordName;
				ws.Cell(row + startIdx + 1, 4).Value = data[row].InteractionDescription;
				ws.Cell(row + startIdx + 1, 5).Value = data[row].Quantity;
				ws.Cell(row + startIdx + 1, 6).Value = data[row].Adult;
				ws.Cell(row + startIdx + 1, 7).Value = data[row].Child;
				ws.Cell(row + startIdx + 1, 8).Value = data[row].CustomerName;
				ws.Cell(row + startIdx + 1, 9).Value = data[row].CreationUserName;
				ws.Cell(row + startIdx + 1, 10).Value = data[row].CreationDate;
			}

			MemoryStream XLSStream = new();
			wb.SaveAs(XLSStream);

			await DownloadAync(Evidence_FileName, XLSStream);
		}
		private async Task DownloadAync(string fileName, Stream content)
		{
			content.Position = 0;
			using var streamRef = new DotNetStreamReference(stream: content);
			await _jsRuntime.InvokeVoidAsync("BlazorDownloadFile", $"{fileName}_{DateTime.Today.ToShortDateString()}.xlsx", streamRef);

		}
	}
}
